# Hexo site configuration
title: SSY
subtitle: 记录、思考与分享
description: 一个简洁的个人博客
author: SSY
language: zh-CN
timezone: Asia/Shanghai

url: https://kirahvi03.github.io/personal-hexo-blog
root: /personal-hexo-blog/
permalink: :year/:month/:day/:title/
permalink_defaults:

theme: personal
deploy:
  type: ''

skip_render:
  - README.md
